# Generated by Django 5.2.9 on 2025-12-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('MESSAGE', 'New Message'), ('MENTION', 'Mention'), ('PROJECT', 'Project Update'), ('CHANNEL', 'Channel Activity'), ('MEMBERSHIP', 'Membership Update'), ('SYSTEM', 'System Alert')], default='SYSTEM', max_length=20),
        ),
    ]
