# Generated by Django 5.2.9 on 2025-12-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_professional_role_user_qualifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', help_text="User's timezone", max_length=50),
        ),
    ]
