# Generated by Django 5.2.9 on 2025-12-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_module_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Has the user verified their email address?'),
        ),
    ]
