# Generated by Django 5.2.9 on 2025-12-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Platform Super Admin'), ('ORG_ADMIN', 'Organization Admin'), ('DEPT_HEAD', 'Department Head'), ('TEAM_MANAGER', 'Team Manager'), ('TEAM_MEMBER', 'Team Member')], default='TEAM_MEMBER', help_text="User's role in the organization", max_length=20),
        ),
    ]
