# Generated by Django 5.2.9 on 2026-01-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_database_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('MESSAGE', 'New Message'), ('MENTION', 'Mention'), ('PROJECT', 'Project Update'), ('CHANNEL', 'Channel Activity'), ('MEMBERSHIP', 'Membership Update'), ('CALL', 'Incoming Call'), ('SYSTEM', 'System Alert')], default='SYSTEM', max_length=20),
        ),
    ]
