# Generated by Django 5.2.9 on 2026-01-13 06:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0019_alter_projectfile_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Metric name (e.g., Task Completion Rate)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this metric')),
                ('metric_type', models.CharField(choices=[('NUMERIC', 'Numeric Value'), ('PERCENTAGE', 'Percentage'), ('RATING', 'Rating (1-5)'), ('BOOLEAN', 'Yes/No'), ('THRESHOLD', 'Threshold-based')], default='NUMERIC', help_text='Type of metric', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight/importance of this metric in final score (0.01-10.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10.0)])),
                ('role', models.CharField(blank=True, db_index=True, help_text='Target role for this metric (from User.Role choices)', max_length=20, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is this metric currently active?')),
                ('version', models.IntegerField(default=1, help_text='Metric version for change tracking')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this metric', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_metrics', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organization this metric belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='kpi_metrics', to='organizations.organization')),
                ('team', models.ForeignKey(blank=True, help_text='Specific team this metric applies to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_metrics', to='organizations.team')),
            ],
            options={
                'verbose_name': 'KPI Metric',
                'verbose_name_plural': 'KPI Metrics',
                'db_table': 'kpi_metrics',
                'ordering': ['organization', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KPIAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_period', models.CharField(help_text="Review period identifier (e.g., '2026-Q1', '2026-01')", max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(help_text='Manager who assigned this metric', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_kpis', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User this metric is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='kpi_assignments', to=settings.AUTH_USER_MODEL)),
                ('metric', models.ForeignKey(help_text='KPI metric being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='performance.kpimetric')),
            ],
            options={
                'verbose_name': 'KPI Assignment',
                'verbose_name_plural': 'KPI Assignments',
                'db_table': 'kpi_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='KPIThreshold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum acceptable value', max_digits=10, null=True)),
                ('target_value', models.DecimalField(decimal_places=2, help_text='Target/expected value', max_digits=10)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum possible/optimal value', max_digits=10, null=True)),
                ('pass_fail_enabled', models.BooleanField(default=False, help_text='Enable pass/fail evaluation based on min_value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.OneToOneField(help_text='KPI metric this threshold applies to', on_delete=django.db.models.deletion.CASCADE, related_name='threshold', to='performance.kpimetric')),
            ],
            options={
                'verbose_name': 'KPI Threshold',
                'verbose_name_plural': 'KPI Thresholds',
                'db_table': 'kpi_thresholds',
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_period_start', models.DateField(db_index=True, help_text='Start date of review period')),
                ('review_period_end', models.DateField(db_index=True, help_text='End date of review period')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, help_text='Aggregated weighted score (0-100)', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized')], db_index=True, default='DRAFT', help_text='Review status', max_length=20)),
                ('comments', models.TextField(blank=True, help_text="Reviewer's overall comments and feedback")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, help_text='When this review was finalized', null=True)),
                ('organization', models.ForeignKey(help_text='Organization context', on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='organizations.organization')),
                ('reviewer', models.ForeignKey(help_text='Manager conducting the review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performance Review',
                'verbose_name_plural': 'Performance Reviews',
                'db_table': 'performance_reviews',
                'ordering': ['-review_period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('METRIC_CREATED', 'Metric Created'), ('METRIC_UPDATED', 'Metric Updated'), ('METRIC_DEACTIVATED', 'Metric Deactivated'), ('ASSIGNMENT_CREATED', 'KPI Assigned'), ('REVIEW_CREATED', 'Review Created'), ('SCORE_CALCULATED', 'Score Calculated'), ('SCORE_OVERRIDDEN', 'Score Overridden'), ('REVIEW_FINALIZED', 'Review Finalized')], db_index=True, help_text='Type of action performed', max_length=30)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the action')),
                ('reason', models.TextField(blank=True, help_text='Reason or justification for the action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_actions', to=settings.AUTH_USER_MODEL)),
                ('metric', models.ForeignKey(blank=True, help_text='Related metric (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='performance.kpimetric')),
                ('organization', models.ForeignKey(help_text='Organization context', on_delete=django.db.models.deletion.CASCADE, related_name='performance_audit_logs', to='organizations.organization')),
                ('target_user', models.ForeignKey(blank=True, help_text='User affected by this action (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_audit_targets', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(blank=True, help_text='Related review (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='performance.performancereview')),
            ],
            options={
                'verbose_name': 'Performance Audit Log',
                'verbose_name_plural': 'Performance Audit Logs',
                'db_table': 'performance_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calculated_score', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated score (0-100)', max_digits=5, null=True)),
                ('manual_override_score', models.DecimalField(blank=True, decimal_places=2, help_text='Manually overridden score (0-100)', max_digits=5, null=True)),
                ('override_reason', models.TextField(blank=True, help_text='Required justification if score is manually overridden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.ForeignKey(help_text='KPI metric being scored', on_delete=django.db.models.deletion.CASCADE, related_name='performance_scores', to='performance.kpimetric')),
                ('overridden_by', models.ForeignKey(blank=True, help_text='User who overrode the score', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_overrides', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(help_text='Parent performance review', on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='performance.performancereview')),
            ],
            options={
                'verbose_name': 'Performance Score',
                'verbose_name_plural': 'Performance Scores',
                'db_table': 'performance_scores',
                'ordering': ['review', 'metric'],
            },
        ),
        migrations.AddIndex(
            model_name='kpimetric',
            index=models.Index(fields=['organization', 'is_active'], name='kpi_metrics_organiz_9fda8d_idx'),
        ),
        migrations.AddIndex(
            model_name='kpimetric',
            index=models.Index(fields=['role', 'is_active'], name='kpi_metrics_role_60c3c8_idx'),
        ),
        migrations.AddIndex(
            model_name='kpiassignment',
            index=models.Index(fields=['user', 'review_period'], name='kpi_assignm_user_id_2d255e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kpiassignment',
            unique_together={('metric', 'user', 'review_period')},
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['user', 'status'], name='performance_user_id_0afa24_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['organization', 'review_period_end'], name='performance_organiz_a2c156_idx'),
        ),
        migrations.AddIndex(
            model_name='performanceauditlog',
            index=models.Index(fields=['organization', '-timestamp'], name='performance_organiz_30b6f0_idx'),
        ),
        migrations.AddIndex(
            model_name='performanceauditlog',
            index=models.Index(fields=['action', '-timestamp'], name='performance_action_82c4f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='performancescore',
            unique_together={('review', 'metric')},
        ),
    ]
