# Generated by Django 5.2.9 on 2025-12-14 20:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_department_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Channel name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Channel description')),
                ('channel_type', models.CharField(choices=[('OFFICIAL', 'Official Announcement'), ('DEPARTMENT', 'Department Channel'), ('TEAM', 'Team Channel'), ('PROJECT', 'Project Channel'), ('PRIVATE', 'Private Group'), ('DIRECT', 'Direct Message')], default='TEAM', help_text='Type of channel', max_length=20)),
                ('is_private', models.BooleanField(default=False, help_text='Is this a private channel?')),
                ('is_archived', models.BooleanField(default=False, help_text='Is this channel archived?')),
                ('read_only', models.BooleanField(default=False, help_text='Is this channel read-only? (only admins can post)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this channel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channels', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Department (for department channels)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='organizations.department')),
                ('members', models.ManyToManyField(blank=True, help_text='Channel members', related_name='channels', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organization this channel belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='organizations.organization')),
                ('team', models.ForeignKey(blank=True, help_text='Team (for team channels)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='organizations.team')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
                'db_table': 'channels',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
