# Generated by Django 5.2.9 on 2025-12-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_channels', '0002_message_messagereaction_messagereadreceipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='voice_duration',
            field=models.IntegerField(blank=True, help_text='Duration of voice message in seconds', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='voice_message',
            field=models.FileField(blank=True, help_text='Voice message audio file', null=True, upload_to='messages/voice/%Y/%m/%d/'),
        ),
    ]
