# Generated by Django 5.2.9 on 2025-12-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_channels', '0003_message_voice_duration_message_voice_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Message content'),
        ),
    ]
