# Generated by Django 5.2.9 on 2025-12-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_channels', '0007_channel_shared_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the message was deleted', null=True),
        ),
    ]
