# Generated by Django 5.2.9 on 2025-12-25 16:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_channels', '0009_message_deleted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=cloudinary.models.CloudinaryField(help_text='Attached file', max_length=255, verbose_name='file'),
        ),
    ]
