# Generated by Django 5.2.9 on 2025-12-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_channels', '0012_message_forwarded_from_message_is_pinned_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-is_pinned', 'created_at'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
