# Generated by Django 5.2.9 on 2026-01-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_channels', '0015_alter_message_message_type_alter_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(blank=True, choices=[('TEXT', 'Text'), ('EMOJI', 'Emoji'), ('VOICE', 'Voice Note'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('FILE', 'File'), ('SYSTEM', 'System Notice')], db_index=True, default='TEXT', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(blank=True, choices=[('SENDING', 'Sending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], db_index=True, default='SENT', max_length=10, null=True),
        ),
    ]
