# Generated by Django 5.2.9 on 2026-01-02 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_channels', '0018_add_rich_text_formatting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_level', models.CharField(choices=[('ALL', 'All messages'), ('MENTIONS', 'Mentions only'), ('DMS', 'Direct messages only'), ('NOTHING', 'Nothing')], default='ALL', max_length=20)),
                ('is_muted', models.BooleanField(default=False)),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='chat_channels.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Channel Notification Setting',
                'verbose_name_plural': 'Channel Notification Settings',
                'unique_together': {('user', 'channel')},
            },
        ),
    ]
