# Generated by Django 5.2.9 on 2026-01-02 01:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_channels', '0019_channelnotificationsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_type', models.CharField(choices=[('AUDIO', 'Audio Call'), ('VIDEO', 'Video Call'), ('SCREEN', 'Screen Share')], default='AUDIO', max_length=10)),
                ('status', models.CharField(choices=[('INITIATING', 'Initiating'), ('RINGING', 'Ringing'), ('ACTIVE', 'Active'), ('ENDED', 'Ended'), ('MISSED', 'Missed'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], default='INITIATING', max_length=15)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_id', models.CharField(max_length=100, unique=True)),
                ('is_recording', models.BooleanField(default=False)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('channel', models.ForeignKey(blank=True, help_text='Channel for group calls', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='chat_channels.channel')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Call',
                'verbose_name_plural': 'Calls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('RINGING', 'Ringing'), ('JOINED', 'Joined'), ('LEFT', 'Left'), ('REJECTED', 'Rejected'), ('MISSED', 'Missed')], default='INVITED', max_length=10)),
                ('is_audio_enabled', models.BooleanField(default=True)),
                ('is_video_enabled', models.BooleanField(default=True)),
                ('is_screen_sharing', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_records', to='chat_channels.call')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Call Participant',
                'verbose_name_plural': 'Call Participants',
                'unique_together': {('call', 'user')},
            },
        ),
        migrations.AddField(
            model_name='call',
            name='participants',
            field=models.ManyToManyField(related_name='calls', through='chat_channels.CallParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
