# Generated by Django 5.2.9 on 2025-12-14 19:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Organization name', max_length=200, unique=True)),
                ('code', models.CharField(help_text='Unique organization code for signup', max_length=20, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Organization logo', null=True, upload_to='organizations/logos/')),
                ('description', models.TextField(blank=True, help_text='Organization description')),
                ('timezone', models.CharField(default='UTC', help_text='Organization default timezone', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Is this organization active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
    ]
