# Generated by Django 5.2.9 on 2025-12-25 17:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_department_head_alter_team_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Organization logo', max_length=255, null=True, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=cloudinary.models.CloudinaryField(help_text='Shared file', max_length=255, verbose_name='file'),
        ),
    ]
