# Generated by Django 5.2.9 on 2026-01-03 09:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_subscriptiontransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=cloudinary.models.CloudinaryField(help_text='Shared file', max_length=255, verbose_name='file'),
        ),
    ]
